spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

kakao:
  client_id: ${kakao_client_id}
  redirect_uri: ${kakao_redirect_uri}

access:
  secret_key: ${SECRET_KEY}
  token_validity_time: ${ACCESS_TOKEN_VALIDITY_TIME}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG  # Hibernate SQL 실행 로그 출력
        type:
          descriptor:
            sql: TRACE  # SQL 바인딩 변수 로그 출력
