spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

kakao:
  client_id: ${kakao_client_id}
  redirect_uri: ${kakao_redirect_uri}

access:
  secret_key: ${SECRET_KEY}
  token_validity_time: ${ACCESS_TOKEN_VALIDITY_TIME}